spring:
  profiles:
    active: dev   # 테스트, 로컬 환경 나누기+
    include: secret
  datasource:
#    H2
#    url: jdbc:h2:tcp://localhost/~/UX-BOOK-STORE-BACK
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#    Mysql
    url: jdbc:mysql://127.0.0.1:3306/uuzz_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 3MB
      resolve-lazily: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true # 쿼리 다문장 확인
        use_sql_comments: true  # 실행되는 jpql 확인

logging.level:
  org:
    hibernate.SQL: debug
  apache:
    coyote:
      http11: debug
# org.hibernate.type: trace

file:
  dir: /Users/agsoo/file/

