spring:
  profiles:
    active: dev   # 테스트, 로컬 환경 나누기+
    include: secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 3MB
      resolve-lazily: true

logging.level:
  org:
    hibernate.SQL: debug
  apache:
    coyote:
      http11: debug
# org.hibernate.type: trace